name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # または master, depending on your default branch
  workflow_dispatch:  # Manual trigger option

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build project
        run: yarn build
        env:
          IMMUTABLE_X_API_URL: ${{ secrets.IMMUTABLE_X_API_URL }}
          IMMUTABLE_X_PUBLISHABLE_KEY: ${{ secrets.IMMUTABLE_X_PUBLISHABLE_KEY }}
          
      - name: Update config.js with environment variables
        run: |
          # Create config script content
          echo '<script>' > dist/config-env.js
          echo '// Site configuration' >> dist/config-env.js
          echo 'window.imxConfig = {' >> dist/config-env.js
          echo '  apiUrl: '"'${{ secrets.IMMUTABLE_X_API_URL || 'https://api.sandbox.immutable.com/v1' }}'"',' >> dist/config-env.js
          echo '  publishableKey: '"'${{ secrets.IMMUTABLE_X_PUBLISHABLE_KEY }}'"'' >> dist/config-env.js
          echo '};' >> dist/config-env.js
          echo '</script>' >> dist/config-env.js
          
          # Insert config into HTML file
          awk '
          {
            print $0
            if ($0 ~ /<!-- Include configuration script first -->/) {
              system("cat dist/config-env.js")
            }
          }' dist/index.html > dist/temp.html
          mv dist/temp.html dist/index.html
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}